### ISSUE TITLE
just a q

### ISSUE THREAD

**Issue by HassanDev13** [Asutosh11/DocumentReader#1]
awsome work thanks bro , but how i can display pdf file for example in sreen ?

**Comment by Asutosh11** [comment]
The Library extracts the text content of a PDF and returns it in String format. You can use that String anywhere to show the content. Please note that, this library won't extract anything other than text data from the PDF. If you have images in PDF this library won't extract it.. 

I hope this clarifies your doubt.

**Comment by HassanDev13** [comment]
ah i get you thanks bro so any solution for images  ? how we can handler them in this case ?

**Comment by Asutosh11** [comment]
For images, as of now I haven't thought anything. My Library is built on top of Apache Tika. See if they support images, then we can go for a feature addition. Else you need to see some other solution.
